#!/usr/bin/env python3
"""Map raw ``readAllMinParam`` keys to human-readable labels and join live values.

Reads a saved probe JSON (from ``fetch_min_params.py``), writes a markdown table
to stdout and optionally to ``audit/explore/``.

Usage:
    python scripts/explore/map_read_all_min_param.py
    python scripts/explore/map_read_all_min_param.py audit/explore/20260403_132837_read_all_min_param.json
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent.parent
sys.path.insert(0, str(_HERE))

from min_param_key_label import describe_key  # noqa: E402

_AUDIT = _REPO / "audit" / "explore"


def _load_msg(path: Path) -> dict[str, str]:
    data = json.loads(path.read_text())
    body = data.get("response", {}).get("body") or {}
    msg = body.get("msg")
    if not isinstance(msg, dict):
        raise SystemExit(f"No response.body.msg object in {path}")
    # Normalise values to strings for display
    return {k: str(v) for k, v in msg.items()}


def _md_table(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "| Raw key | Value | Readable name | Group |",
        "|---------|-------|---------------|-------|",
    ]
    for key, val, label, group in rows:
        safe_val = val.replace("|", "\\|").replace("\n", " ")
        if len(safe_val) > 48:
            safe_val = safe_val[:45] + "…"
        safe_label = label.replace("|", "\\|")
        lines.append(f"| `{key}` | {safe_val} | {safe_label} | {group} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Map readAllMinParam keys to labels.")
    ap.add_argument(
        "json_path",
        nargs="?",
        default=None,
        help="Path to probe JSON (default: newest *_read_all_min_param.json under audit/explore/)",
    )
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Write markdown report to this path (default: audit/explore/<ts>_min_param_map.md)",
    )
    args = ap.parse_args()

    if args.json_path:
        src = Path(args.json_path).resolve()
    else:
        candidates = sorted(_AUDIT.glob("*_read_all_min_param.json"), key=lambda p: p.stat().st_mtime)
        if not candidates:
            print("ERROR: no *_read_all_min_param.json under audit/explore/", file=sys.stderr)
            return 1
        src = candidates[-1]

    msg = _load_msg(src)
    rows: list[tuple[str, str, str, str]] = []
    for key in sorted(msg.keys()):
        label, group = describe_key(key)
        rows.append((key, msg[key], label, group))

    header = (
        f"<!-- Generated by map_read_all_min_param.py — {datetime.now().isoformat(timespec='seconds')} -->\n"
        f"**Source:** `{src.relative_to(_REPO)}`  \n"
        f"**Keys:** {len(rows)}  \n\n"
    )

    report = header + _md_table(rows)
    print(report)

    out = args.output
    if out is None:
        _AUDIT.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out = _AUDIT / f"{ts}_min_param_map.md"

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"\nWrote {out.relative_to(_REPO)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
